### ISSUE TITLE
Add support for custom filter

### ISSUE THREAD

**Issue by MichaelTSS** [spacefill/gibbon-mail#7]
As a gibbon-mail user, I would like to use my custom nunjunks filters.

# Todo

- [x] create a placeholder for outside custom filters to site : `backend/filters/`
- [x] Load all filters from this directory, if any
- [x] update README.md
